### ISSUE TITLE
import FileDropComponent from ??????

### ISSUE THREAD

**Issue by shajiparameswaran** [maheshpolus/file-drop#1]
Hi Mahesh,

Could you please have a look at the first import statement ?
The component "FileDropComponent " is imported from "./file-drop/**app-elastic.component**" which actually does not exist.
I think it should be like 
import { FileDropComponent } from './file-drop/**file-drop.component**';

Thanks
Shaji

**Comment by maheshpolus** [comment]
Typo fixed 
Thanks
